export const VIDEO_START_PLAYING = "VIDEO_START_PLAYING"
export const VIDEO_END_VIDEO = "VIDEO_END_VIDEO"

export const POPUP_DESTROY = "POPUP_DESTROY"
export const POPUP_NOT_PUSHED = "POPUP_NOT_PUSHED"
export const POPUP_PUSH = "POPUP_PUSH"
